<?php

namespace Sprint\Migration;


class Version20210114170145 extends Version
{
    protected $description = "";

    protected $moduleVersion = "3.16.3";

    /**
     * @throws Exceptions\HelperException
     * @return bool|void
     */
    public function up()
    {
        $helper = $this->getHelperManager();
        $helper->Iblock()->saveIblockType(array (
  'ID' => 'aspro_mshop_catalog',
  'SECTIONS' => 'Y',
  'EDIT_FILE_BEFORE' => NULL,
  'EDIT_FILE_AFTER' => NULL,
  'IN_RSS' => 'N',
  'SORT' => '100',
  'LANG' => 
  array (
    'ru' => 
    array (
      'NAME' => 'Каталог',
      'SECTION_NAME' => 'Разделы',
      'ELEMENT_NAME' => 'Товары',
    ),
    'en' => 
    array (
      'NAME' => 'Каталог',
      'SECTION_NAME' => 'Разделы',
      'ELEMENT_NAME' => 'Товары',
    ),
  ),
));
        $iblockId = $helper->Iblock()->saveIblock(array (
  'IBLOCK_TYPE_ID' => 'aspro_mshop_catalog',
  'LID' => 
  array (
    0 => 's1',
  ),
  'CODE' => 'aspro_mshop_catalog',
  'API_CODE' => NULL,
  'NAME' => 'Основной каталог товаров',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'LIST_PAGE_URL' => '/catalog/',
  'DETAIL_PAGE_URL' => '/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/',
  'SECTION_PAGE_URL' => '/catalog/#SECTION_CODE_PATH#/',
  'CANONICAL_PAGE_URL' => '',
  'PICTURE' => NULL,
  'DESCRIPTION' => 'Основной каталог товаров',
  'DESCRIPTION_TYPE' => 'html',
  'RSS_TTL' => '24',
  'RSS_ACTIVE' => 'Y',
  'RSS_FILE_ACTIVE' => 'N',
  'RSS_FILE_LIMIT' => NULL,
  'RSS_FILE_DAYS' => NULL,
  'RSS_YANDEX_ACTIVE' => 'N',
  'XML_ID' => '95ed3ae0-fafb-4a14-9290-73cf281c845c',
  'INDEX_ELEMENT' => 'Y',
  'INDEX_SECTION' => 'Y',
  'WORKFLOW' => 'N',
  'BIZPROC' => 'N',
  'SECTION_CHOOSER' => 'L',
  'LIST_MODE' => 'C',
  'RIGHTS_MODE' => 'S',
  'SECTION_PROPERTY' => 'Y',
  'PROPERTY_INDEX' => 'I',
  'VERSION' => '1',
  'LAST_CONV_ELEMENT' => '0',
  'SOCNET_GROUP_ID' => NULL,
  'EDIT_FILE_BEFORE' => '/bitrix/php_interface/include/iblock_catalog_edit_after_save.php',
  'EDIT_FILE_AFTER' => '',
  'SECTIONS_NAME' => 'Разделы',
  'SECTION_NAME' => 'Раздел',
  'ELEMENTS_NAME' => 'Товары',
  'ELEMENT_NAME' => 'Товар',
  'EXTERNAL_ID' => '95ed3ae0-fafb-4a14-9290-73cf281c845c',
  'LANG_DIR' => '/',
  'SERVER_NAME' => 'ducktex.ru',
  'ELEMENT_ADD' => 'Добавить товар',
  'ELEMENT_EDIT' => 'Изменить товар',
  'ELEMENT_DELETE' => 'Удалить товар',
  'SECTION_ADD' => 'Добавить раздел',
  'SECTION_EDIT' => 'Изменить раздел',
  'SECTION_DELETE' => 'Удалить раздел',
));
        $helper->Iblock()->saveIblockFields($iblockId, array (
  'IBLOCK_SECTION' => 
  array (
    'NAME' => 'Привязка к разделам',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'KEEP_IBLOCK_SECTION_ID' => 'N',
    ),
  ),
  'ACTIVE' => 
  array (
    'NAME' => 'Активность',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'Y',
  ),
  'ACTIVE_FROM' => 
  array (
    'NAME' => 'Начало активности',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '=today',
  ),
  'ACTIVE_TO' => 
  array (
    'NAME' => 'Окончание активности',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'SORT' => 
  array (
    'NAME' => 'Сортировка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '0',
  ),
  'NAME' => 
  array (
    'NAME' => 'Название',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
  ),
  'PREVIEW_PICTURE' => 
  array (
    'NAME' => 'Картинка для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'FROM_DETAIL' => 'Y',
      'SCALE' => 'N',
      'WIDTH' => 170,
      'HEIGHT' => 170,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 95,
      'DELETE_WITH_DETAIL' => 'Y',
      'UPDATE_WITH_DETAIL' => 'Y',
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => 'tl',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => 'tl',
      'WATERMARK_FILE_ORDER' => NULL,
    ),
  ),
  'PREVIEW_TEXT_TYPE' => 
  array (
    'NAME' => 'Тип описания для анонса',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'text',
  ),
  'PREVIEW_TEXT' => 
  array (
    'NAME' => 'Описание для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'DETAIL_PICTURE' => 
  array (
    'NAME' => 'Детальная картинка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'SCALE' => 'Y',
      'WIDTH' => 1280,
      'HEIGHT' => 1280,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 75,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => 'tl',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => 'tl',
      'WATERMARK_FILE_ORDER' => NULL,
    ),
  ),
  'DETAIL_TEXT_TYPE' => 
  array (
    'NAME' => 'Тип детального описания',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'text',
  ),
  'DETAIL_TEXT' => 
  array (
    'NAME' => 'Детальное описание',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'XML_ID' => 
  array (
    'NAME' => 'Внешний код',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
  ),
  'CODE' => 
  array (
    'NAME' => 'Символьный код',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'UNIQUE' => 'Y',
      'TRANSLITERATION' => 'Y',
      'TRANS_LEN' => 100,
      'TRANS_CASE' => 'L',
      'TRANS_SPACE' => '_',
      'TRANS_OTHER' => '_',
      'TRANS_EAT' => 'Y',
      'USE_GOOGLE' => 'N',
    ),
  ),
  'TAGS' => 
  array (
    'NAME' => 'Теги',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'SECTION_NAME' => 
  array (
    'NAME' => 'Название',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => '',
  ),
  'SECTION_PICTURE' => 
  array (
    'NAME' => 'Картинка для анонса',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'FROM_DETAIL' => 'Y',
      'SCALE' => 'N',
      'WIDTH' => 120,
      'HEIGHT' => 120,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 95,
      'DELETE_WITH_DETAIL' => 'Y',
      'UPDATE_WITH_DETAIL' => 'Y',
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => 'tl',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => 'tl',
      'WATERMARK_FILE_ORDER' => NULL,
    ),
  ),
  'SECTION_DESCRIPTION_TYPE' => 
  array (
    'NAME' => 'Тип описания',
    'IS_REQUIRED' => 'Y',
    'DEFAULT_VALUE' => 'text',
  ),
  'SECTION_DESCRIPTION' => 
  array (
    'NAME' => 'Описание',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'SECTION_DETAIL_PICTURE' => 
  array (
    'NAME' => 'Детальная картинка',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'SCALE' => 'Y',
      'WIDTH' => 2000,
      'HEIGHT' => 2000,
      'IGNORE_ERRORS' => 'N',
      'METHOD' => 'resample',
      'COMPRESSION' => 95,
      'USE_WATERMARK_TEXT' => 'N',
      'WATERMARK_TEXT' => '',
      'WATERMARK_TEXT_FONT' => '',
      'WATERMARK_TEXT_COLOR' => '',
      'WATERMARK_TEXT_SIZE' => '',
      'WATERMARK_TEXT_POSITION' => 'tl',
      'USE_WATERMARK_FILE' => 'N',
      'WATERMARK_FILE' => '',
      'WATERMARK_FILE_ALPHA' => '',
      'WATERMARK_FILE_POSITION' => 'tl',
      'WATERMARK_FILE_ORDER' => NULL,
    ),
  ),
  'SECTION_XML_ID' => 
  array (
    'NAME' => 'Внешний код',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => '',
  ),
  'SECTION_CODE' => 
  array (
    'NAME' => 'Символьный код',
    'IS_REQUIRED' => 'N',
    'DEFAULT_VALUE' => 
    array (
      'UNIQUE' => 'N',
      'TRANSLITERATION' => 'N',
      'TRANS_LEN' => 100,
      'TRANS_CASE' => 'L',
      'TRANS_SPACE' => '_',
      'TRANS_OTHER' => '_',
      'TRANS_EAT' => 'Y',
      'USE_GOOGLE' => 'N',
    ),
  ),
));
    $helper->Iblock()->saveGroupPermissions($iblockId, array (
  'administrators' => 'X',
  'everyone' => 'R',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Минимальная цена',
  'ACTIVE' => 'Y',
  'SORT' => '1',
  'CODE' => 'MINIMUM_PRICE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4896',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Максимальная цена',
  'ACTIVE' => 'Y',
  'SORT' => '2',
  'CODE' => 'MAXIMUM_PRICE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4897',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Наши предложения',
  'ACTIVE' => 'Y',
  'SORT' => '10',
  'CODE' => 'HIT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'Y',
  'XML_ID' => '0004-bestseller',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'Y',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Хит',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => 'HIT',
    ),
    1 => 
    array (
      'VALUE' => 'Советуем',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => 'RECOMMEND',
    ),
    2 => 
    array (
      'VALUE' => 'Новинка',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => 'NEW',
    ),
    3 => 
    array (
      'VALUE' => 'Акция',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => 'STOCK',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Бренд',
  'ACTIVE' => 'Y',
  'SORT' => '50',
  'CODE' => 'BRAND',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1143',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_mshop_content:aspro_mshop_brands',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Стикер с произвольным значением',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'SALE_TEXT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Температура оттенка',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'TEMPERATURA_OTTENKA',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '8a1c8672-f475-11ea-80e0-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Теплый',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '94e307b6-f475-11ea-80e0-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => 'Холодный',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '94e307b7-f475-11ea-80e0-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Состав',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'SOSTAV',
  'DEFAULT_VALUE' => NULL,
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '11ce4588-13eb-11eb-80e1-00155d300e0d',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => NULL,
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => NULL,
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => NULL,
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => '70% хлопок 30% полиэстер',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '2769956b-13eb-11eb-80e1-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => '92% хлопок 8% лайкра',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '305cc906-13eb-11eb-80e1-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => '95% хлопок 5% лайкра',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '3c3f0169-13eb-11eb-80e1-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => '100% хлопок',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '3c3f016a-13eb-11eb-80e1-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => '100% полиэстер',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '93f9e1c5-16ff-11eb-80e1-00155d300e0d',
    ),
    5 => 
    array (
      'VALUE' => '65% хлопок 30% полиэстер 5% лайкра',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '82739647-4551-11eb-80e3-00155d300e0d',
    ),
    6 => 
    array (
      'VALUE' => '73% полиэстер 21% вискоза 6% спандекс',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '8483af88-2f6d-11eb-80e2-00155d300e0d',
    ),
    7 => 
    array (
      'VALUE' => '85% хлопок 15% полиэстер',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '8ad572fd-1fab-11eb-80e2-00155d300e0d',
    ),
    8 => 
    array (
      'VALUE' => '90% хлопок 10% полиэстер',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '4ac3f380-13eb-11eb-80e1-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Коэффициент единицы измерения',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'KOEFFITSIENT_EDINITSY_IZMERENIYA',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1ef1f60a-db95-11e8-80c9-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => '0,1',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '2d938add-ef91-11ea-80e0-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => '0,5',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '26ef95d0-db95-11e8-80c9-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => '1',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => 'a94e1f4f-fb65-11ea-80e1-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => '0,1',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '4b070941-db95-11e8-80c9-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => '1',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '4b070942-db95-11e8-80c9-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'ВидНоменклатуры',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'VIDNOMENKLATURY_ATTR_S',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'VIDNOMENKLATURY_ATTR_S',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'ТипНоменклатуры',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'TIPNOMENKLATURY_ATTR_S',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'TIPNOMENKLATURY_ATTR_S',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Код',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'KOD_ATTR_S',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'KOD_ATTR_S',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Вес',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'VES_ATTR_S',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'VES_ATTR_S',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Связанная номенклатура',
  'ACTIVE' => 'Y',
  'SORT' => '100',
  'CODE' => 'SVYAZANNAYA_NOMENKLATURA_ATTR_S',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'SVYAZANNAYA_NOMENKLATURA_ATTR_S',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Ширина',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'SHIRINA',
  'DEFAULT_VALUE' => NULL,
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '5d9d8b16-13eb-11eb-80e1-00155d300e0d',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => NULL,
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => NULL,
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => NULL,
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => '180см',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '5d9d8b17-13eb-11eb-80e1-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => '70см*2 (чулок)',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '6dabe1af-13eb-11eb-80e1-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => '65см*2 (чулок)',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '76067f97-13eb-11eb-80e1-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => '120см',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '76067f98-13eb-11eb-80e1-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => '140см',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '805a8ecc-13eb-11eb-80e1-00155d300e0d',
    ),
    5 => 
    array (
      'VALUE' => '30мм',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '8475bcca-14ab-11eb-80e1-00155d300e0d',
    ),
    6 => 
    array (
      'VALUE' => '50мм',
      'DEF' => 'N',
      'SORT' => '600',
      'XML_ID' => 'f0c10ca8-14ab-11eb-80e1-00155d300e0d',
    ),
    7 => 
    array (
      'VALUE' => '20мм',
      'DEF' => 'N',
      'SORT' => '700',
      'XML_ID' => '20b3d221-14ac-11eb-80e1-00155d300e0d',
    ),
    8 => 
    array (
      'VALUE' => '45мм',
      'DEF' => 'N',
      'SORT' => '800',
      'XML_ID' => '3d694866-14ac-11eb-80e1-00155d300e0d',
    ),
    9 => 
    array (
      'VALUE' => '40мм',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => '56720a53-14ac-11eb-80e1-00155d300e0d',
    ),
    10 => 
    array (
      'VALUE' => '25мм',
      'DEF' => 'N',
      'SORT' => '1000',
      'XML_ID' => '75f3acb7-14ac-11eb-80e1-00155d300e0d',
    ),
    11 => 
    array (
      'VALUE' => '12мм',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => '9ce38c34-16ff-11eb-80e1-00155d300e0d',
    ),
    12 => 
    array (
      'VALUE' => '13мм',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => 'a124a1bc-16fe-11eb-80e1-00155d300e0d',
    ),
    13 => 
    array (
      'VALUE' => '15мм',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => '057fed59-2e50-11eb-80e2-00155d300e0d',
    ),
    14 => 
    array (
      'VALUE' => '60см*2 (чулок)',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => 'f261a0c5-1756-11eb-80e1-00155d300e0d',
    ),
    15 => 
    array (
      'VALUE' => '6мм',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => 'b947e2d1-33de-11eb-80e2-00155d300e0d',
    ),
    16 => 
    array (
      'VALUE' => '8мм',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => 'b1ebfcc2-38c9-11eb-80e3-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Качество',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'KACHESTVO',
  'DEFAULT_VALUE' => NULL,
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '9b13b5e8-3b30-11eb-80e3-00155d300e0d',
  'FILE_TYPE' => NULL,
  'MULTIPLE_CNT' => NULL,
  'LINK_IBLOCK_ID' => NULL,
  'WITH_DESCRIPTION' => NULL,
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => NULL,
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => NULL,
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Компакт',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '9b13b5e9-3b30-11eb-80e3-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => 'Пенье',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => 'a35da2d3-3b30-11eb-80e3-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цвет',
  'ACTIVE' => 'Y',
  'SORT' => '200',
  'CODE' => 'TSVET',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '02462eb5-9932-11ea-80df-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Коричневый',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '52a237d6-ef91-11ea-80e0-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => 'Синий',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '02462eb6-9932-11ea-80df-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => 'Красный/Бордо',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '09df656e-9932-11ea-80df-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => 'Серый',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '4d646b92-ef92-11ea-80e0-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => 'Белый',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '09df656f-9932-11ea-80df-00155d300e0d',
    ),
    5 => 
    array (
      'VALUE' => 'Фисташка',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => 'ed308cdb-d3d6-11ea-80e0-00155d300e0d',
    ),
    6 => 
    array (
      'VALUE' => 'Черный',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => 'e93b8300-ef93-11ea-80e0-00155d300e0d',
    ),
    7 => 
    array (
      'VALUE' => 'Красный/Бордо',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '5362732e-ef94-11ea-80e0-00155d300e0d',
    ),
    8 => 
    array (
      'VALUE' => 'Лаванда',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '8615ba6f-d3d7-11ea-80e0-00155d300e0d',
    ),
    9 => 
    array (
      'VALUE' => 'Синий',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '3dc07c2f-ef95-11ea-80e0-00155d300e0d',
    ),
    10 => 
    array (
      'VALUE' => 'Черный',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'c586cd4e-d3d7-11ea-80e0-00155d300e0d',
    ),
    11 => 
    array (
      'VALUE' => 'Зеленый',
      'DEF' => 'N',
      'SORT' => '600',
      'XML_ID' => 'eab35085-ef96-11ea-80e0-00155d300e0d',
    ),
    12 => 
    array (
      'VALUE' => 'Розовый',
      'DEF' => 'N',
      'SORT' => '600',
      'XML_ID' => '4c34b577-d3d8-11ea-80e0-00155d300e0d',
    ),
    13 => 
    array (
      'VALUE' => 'Бежевый',
      'DEF' => 'N',
      'SORT' => '700',
      'XML_ID' => '18bc773f-ef9c-11ea-80e0-00155d300e0d',
    ),
    14 => 
    array (
      'VALUE' => 'Коричневый',
      'DEF' => 'N',
      'SORT' => '700',
      'XML_ID' => 'd46a9881-db4e-11ea-80e0-00155d300e0d',
    ),
    15 => 
    array (
      'VALUE' => 'Розовый',
      'DEF' => 'N',
      'SORT' => '800',
      'XML_ID' => 'bd7812fe-ef9c-11ea-80e0-00155d300e0d',
    ),
    16 => 
    array (
      'VALUE' => 'Фиолетовый',
      'DEF' => 'N',
      'SORT' => '800',
      'XML_ID' => 'df062dcd-db4e-11ea-80e0-00155d300e0d',
    ),
    17 => 
    array (
      'VALUE' => 'Бежевый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'c96fd570-e00e-11ea-80e0-00155d300e0d',
    ),
    18 => 
    array (
      'VALUE' => 'Белый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => '190bad14-efa6-11ea-80e0-00155d300e0d',
    ),
    19 => 
    array (
      'VALUE' => 'Голубой',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => '824bab38-e012-11ea-80e0-00155d300e0d',
    ),
    20 => 
    array (
      'VALUE' => 'Желтый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'e7cdcb84-de31-11ea-80e0-00155d300e0d',
    ),
    21 => 
    array (
      'VALUE' => 'Зеленый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'ec5eb605-db4e-11ea-80e0-00155d300e0d',
    ),
    22 => 
    array (
      'VALUE' => 'Оранжевый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => '828a52ca-e0cd-11ea-80e0-00155d300e0d',
    ),
    23 => 
    array (
      'VALUE' => 'Серый',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'cd245f76-e010-11ea-80e0-00155d300e0d',
    ),
    24 => 
    array (
      'VALUE' => 'Красный',
      'DEF' => 'N',
      'SORT' => '1000',
      'XML_ID' => '92aaf291-efa7-11ea-80e0-00155d300e0d',
    ),
    25 => 
    array (
      'VALUE' => 'Оранжевый',
      'DEF' => 'N',
      'SORT' => '1100',
      'XML_ID' => 'ad9ee1cd-efac-11ea-80e0-00155d300e0d',
    ),
    26 => 
    array (
      'VALUE' => 'Фиолетовый',
      'DEF' => 'N',
      'SORT' => '1200',
      'XML_ID' => 'ec9adeeb-f05d-11ea-80e0-00155d300e0d',
    ),
    27 => 
    array (
      'VALUE' => 'Голубой',
      'DEF' => 'N',
      'SORT' => '1300',
      'XML_ID' => 'de8f8576-3b30-11eb-80e3-00155d300e0d',
    ),
    28 => 
    array (
      'VALUE' => 'Желтый',
      'DEF' => 'N',
      'SORT' => '1300',
      'XML_ID' => 'db42a112-f060-11ea-80e0-00155d300e0d',
    ),
    29 => 
    array (
      'VALUE' => 'Мультиколор',
      'DEF' => 'N',
      'SORT' => '1300',
      'XML_ID' => '6ce1d269-4551-11eb-80e3-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Плотность',
  'ACTIVE' => 'Y',
  'SORT' => '300',
  'CODE' => 'PLOTNOST',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '2ed29e58-9a17-11ea-80df-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => '',
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => '200гр',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '5aca5d8d-9a17-11ea-80df-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => '260 гр',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '5df7c5ac-ef91-11ea-80e0-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => '200 гр',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '1ffb95c1-efa6-11ea-80e0-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => '350гр',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '677e64f7-9a17-11ea-80df-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => '230 гр',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '3289a65f-efb1-11ea-80e0-00155d300e0d',
    ),
    5 => 
    array (
      'VALUE' => '260гр',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '752f2942-9a17-11ea-80df-00155d300e0d',
    ),
    6 => 
    array (
      'VALUE' => '330гр',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '80662f90-9a17-11ea-80df-00155d300e0d',
    ),
    7 => 
    array (
      'VALUE' => '350 гр',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '83bcf25b-f05d-11ea-80e0-00155d300e0d',
    ),
    8 => 
    array (
      'VALUE' => '230гр',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '778d912d-db51-11ea-80e0-00155d300e0d',
    ),
    9 => 
    array (
      'VALUE' => '330 гр',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '7c0ab6da-f060-11ea-80e0-00155d300e0d',
    ),
    10 => 
    array (
      'VALUE' => '340 гр',
      'DEF' => 'N',
      'SORT' => '600',
      'XML_ID' => '01dd30eb-f066-11ea-80e0-00155d300e0d',
    ),
    11 => 
    array (
      'VALUE' => '340гр',
      'DEF' => 'N',
      'SORT' => '600',
      'XML_ID' => '778d912e-db51-11ea-80e0-00155d300e0d',
    ),
    12 => 
    array (
      'VALUE' => '400 гр',
      'DEF' => 'N',
      'SORT' => '700',
      'XML_ID' => '56c48253-f28e-11ea-80e0-00155d300e0d',
    ),
    13 => 
    array (
      'VALUE' => '400гр',
      'DEF' => 'N',
      'SORT' => '700',
      'XML_ID' => '8217e135-db51-11ea-80e0-00155d300e0d',
    ),
    14 => 
    array (
      'VALUE' => '160 гр',
      'DEF' => 'N',
      'SORT' => '800',
      'XML_ID' => 'f12fd6e7-f3a0-11ea-80e0-00155d300e0d',
    ),
    15 => 
    array (
      'VALUE' => '250 гр',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'f358b77d-2d77-11eb-80e2-00155d300e0d',
    ),
    16 => 
    array (
      'VALUE' => '360гр',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => '71dd755a-1fab-11eb-80e2-00155d300e0d',
    ),
    17 => 
    array (
      'VALUE' => '370 гр',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'cdd7fa2d-1755-11eb-80e1-00155d300e0d',
    ),
    18 => 
    array (
      'VALUE' => '460 гр',
      'DEF' => 'N',
      'SORT' => '900',
      'XML_ID' => 'c207ae00-068c-11eb-80e1-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цвет ткани',
  'ACTIVE' => 'Y',
  'SORT' => '300',
  'CODE' => 'TSVET_TKANI',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '7c3e33ac-9934-11ea-80df-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Белый',
      'DEF' => 'N',
      'SORT' => '100',
      'XML_ID' => '7c3e33ad-9934-11ea-80df-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => 'Красный',
      'DEF' => 'N',
      'SORT' => '200',
      'XML_ID' => '8584d82b-9934-11ea-80df-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => 'Зеленый',
      'DEF' => 'N',
      'SORT' => '300',
      'XML_ID' => '8584d82c-9934-11ea-80df-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => 'Черный',
      'DEF' => 'N',
      'SORT' => '400',
      'XML_ID' => '8ddab0e2-9934-11ea-80df-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'В наличии',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'IN_STOCK',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '113330',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Y',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'Y',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Тип',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'PROP_2033',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1199',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Количество проголосовавших',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'vote_count',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4883',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Сумма оценок',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'vote_sum',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4884',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Рейтинг',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'rating',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4885',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Видео (код из Youtube)',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'VIDEO_YOUTUBE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '4887',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Услуги',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'SERVICES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '4890',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_mshop_content:aspro_mshop_services',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Тема форума для комментариев',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'FORUM_TOPIC_ID',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4891',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Количество комментариев к элементу',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'FORUM_MESSAGE_CNT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '4892',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Артикул',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_ARTICLE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'CML2_ARTICLE',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Реквизиты',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_TRAITS',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'CML2_TRAITS',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Базовая единица',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_BASE_UNIT',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'CML2_BASE_UNIT',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Ставки налогов',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_TAXES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'CML2_TAXES',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Картинки',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'MORE_PHOTO',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'CML2_PICTURES',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Файлы',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'FILES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'F',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'CML2_FILES',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Аксессуары',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'EXPANDABLES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => '1257',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_mshop_catalog:aspro_mshop_catalog',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Характеристики',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_ATTRIBUTES',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'CML2_ATTRIBUTES',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'Y',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Цвет',
  'ACTIVE' => 'N',
  'SORT' => '500',
  'CODE' => 'COLOR_REF2',
  'DEFAULT_VALUE' => 'purple',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '183',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => 'directory',
  'USER_TYPE_SETTINGS' => 
  array (
    'size' => 1,
    'width' => 0,
    'group' => 'N',
    'multiple' => 'N',
    'TABLE_NAME' => 'mshop_color_reference',
  ),
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'ШтрихКод',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'CML2_BAR_CODE',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'CML2_BAR_CODE',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Производитель',
  'ACTIVE' => 'N',
  'SORT' => '500',
  'CODE' => 'CML2_MANUFACTURER',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'CML2_MANUFACTURER',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '1',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Белоруссия',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '7a31b552-820e-11ea-80d9-00155d300e0d',
    ),
    1 => 
    array (
      'VALUE' => 'Германия',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'dfe35330-cd4d-11e8-80c9-00155d300e0d',
    ),
    2 => 
    array (
      'VALUE' => 'Италия',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '56349d9d-96bd-11e9-80cf-00155d300e0d',
    ),
    3 => 
    array (
      'VALUE' => 'Китай',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => '02e30a97-d057-11e8-80c9-00155d300e0d',
    ),
    4 => 
    array (
      'VALUE' => 'Корея',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'e025991c-c52a-11e9-80d1-00155d300e0d',
    ),
    5 => 
    array (
      'VALUE' => 'Польша',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'b1cfc086-f5b7-11e8-80ca-00155d300e0d',
    ),
    6 => 
    array (
      'VALUE' => 'Турция',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'dfe3532f-cd4d-11e8-80c9-00155d300e0d',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Похожие товары',
  'ACTIVE' => 'Y',
  'SORT' => '500',
  'CODE' => 'ASSOCIATED',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'E',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'Y',
  'XML_ID' => 'c80b6752-d8ea-11e8-80c9-00155d300e0d',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => 'aspro_mshop_catalog:aspro_mshop_catalog',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Вес, кг',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_159',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'df5088b3-c4c0-11e1-ade8-0018f30e135a',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Площадь обработки, м2',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_162',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => 'df5088bb-c4c0-11e1-ade8-0018f30e135a',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Тип управления',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2017',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1183',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Объем, л',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2026',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1192',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Гриль',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2027',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1193',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Оптическое увеличение',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2044',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1213',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Модель',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2049',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1218',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Воспроизведение видео',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2052',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'L',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'C',
  'MULTIPLE' => 'N',
  'XML_ID' => '1221',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
  'VALUES' => 
  array (
    0 => 
    array (
      'VALUE' => 'Да',
      'DEF' => 'N',
      'SORT' => '500',
      'XML_ID' => 'yes',
    ),
  ),
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Диагональ дисплея',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2053',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'N',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1222',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Разрешение дисплея',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2054',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1223',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Размер',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2065',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1235',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->Iblock()->saveProperty($iblockId, array (
  'NAME' => 'Материал',
  'ACTIVE' => 'Y',
  'SORT' => '5000',
  'CODE' => 'PROP_2083',
  'DEFAULT_VALUE' => '',
  'PROPERTY_TYPE' => 'S',
  'ROW_COUNT' => '1',
  'COL_COUNT' => '30',
  'LIST_TYPE' => 'L',
  'MULTIPLE' => 'N',
  'XML_ID' => '1253',
  'FILE_TYPE' => '',
  'MULTIPLE_CNT' => '5',
  'LINK_IBLOCK_ID' => '0',
  'WITH_DESCRIPTION' => 'N',
  'SEARCHABLE' => 'N',
  'FILTRABLE' => 'N',
  'IS_REQUIRED' => 'N',
  'VERSION' => '1',
  'USER_TYPE' => NULL,
  'USER_TYPE_SETTINGS' => NULL,
  'HINT' => '',
));
        $helper->UserOptions()->saveSectionForm($iblockId, array (
  'Раздел|edit1' => 
  array (
    'ID' => 'ID',
    'DATE_CREATE' => 'Создан',
    'TIMESTAMP_X' => 'Изменен',
    'CODE' => 'Символьный код',
    'ACTIVE' => 'Раздел активен',
    'IBLOCK_SECTION_ID' => 'Родительский раздел',
    'NAME' => 'Название',
    'PICTURE' => 'Изображение',
    'DESCRIPTION' => 'Описание',
  ),
  'SEO|edit5' => 
  array (
    'IPROPERTY_TEMPLATES_SECTION' => 'Настройки для разделов',
    'IPROPERTY_TEMPLATES_SECTION_META_TITLE' => 'Шаблон META TITLE',
    'IPROPERTY_TEMPLATES_SECTION_META_KEYWORDS' => 'Шаблон META KEYWORDS',
    'IPROPERTY_TEMPLATES_SECTION_META_DESCRIPTION' => 'Шаблон META DESCRIPTION',
    'IPROPERTY_TEMPLATES_SECTION_PAGE_TITLE' => 'Заголовок раздела',
    'IPROPERTY_TEMPLATES_ELEMENT' => 'Настройки для элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_META_TITLE' => 'Шаблон META TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_META_KEYWORDS' => 'Шаблон META KEYWORDS',
    'IPROPERTY_TEMPLATES_ELEMENT_META_DESCRIPTION' => 'Шаблон META DESCRIPTION',
    'IPROPERTY_TEMPLATES_ELEMENT_PAGE_TITLE' => 'Заголовок товара',
    'IPROPERTY_TEMPLATES_SECTIONS_PICTURE' => 'Настройки для изображений разделов',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_SECTION_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_SECTIONS_DETAIL_PICTURE' => 'Настройки для детальных картинок разделов',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_SECTION_DETAIL_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_ELEMENTS_PREVIEW_PICTURE' => 'Настройки для картинок анонса элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_ELEMENTS_DETAIL_PICTURE' => 'Настройки для детальных картинок элементов',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_ALT' => 'Шаблон ALT',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
    'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_NAME' => 'Шаблон имени файла',
    'IPROPERTY_TEMPLATES_MANAGEMENT' => 'Управление',
    'IPROPERTY_CLEAR_VALUES' => 'Очистить кеш вычисленных значений',
  ),
  'Дополнительно|edit2' => 
  array (
    'SORT' => 'Сортировка',
    'XML_ID' => 'Внешний код',
    'DETAIL_PICTURE' => 'Детальная картинка',
  ),
  'Доп. поля|user_fields_tab' => 
  array (
    'USER_FIELDS_ADD' => 'Добавить пользовательское свойство',
    'UF_SECTION_DESCR' => 'Описание раздела для SEO',
    'UF_SECTION_TEMPLATE' => 'Шаблон списка товаров по умолчанию',
    'UF_OFFERS_TYPE' => 'Тип SKU',
    'UF_ELEMENT_DETAIL' => 'Детальная страница каталога',
    'UF_ON_HOME' => 'Отображать раздел на главной странице',
  ),
  'Свойства элементов|edit4' => 
  array (
    'SECTION_PROPERTY' => 'Свойства элементов',
  ),
));
    $helper->UserOptions()->saveElementGrid($iblockId, array (
  'views' => 
  array (
    'default' => 
    array (
      'columns' => 
      array (
        0 => '',
      ),
      'columns_sizes' => 
      array (
        'expand' => 1,
        'columns' => 
        array (
        ),
      ),
      'sticked_columns' => 
      array (
      ),
    ),
  ),
  'filters' => 
  array (
  ),
  'current_view' => 'default',
));
    $helper->UserOptions()->saveSectionGrid($iblockId, array (
  'views' => 
  array (
    'default' => 
    array (
      'columns' => 
      array (
        0 => '',
      ),
      'columns_sizes' => 
      array (
        'expand' => 1,
        'columns' => 
        array (
        ),
      ),
      'sticked_columns' => 
      array (
      ),
    ),
  ),
  'filters' => 
  array (
  ),
  'current_view' => 'default',
));

    }

    public function down()
    {
        //your code ...
    }
}
