<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Сравнение товаров");
?><?$APPLICATION->IncludeComponent(
	"bitrix:catalog.compare.result", 
	".default", 
	array(
		"ACTION_VARIABLE" => "action",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BASKET_URL" => "/personal/basket.php",
		"CONVERT_CURRENCY" => "N",
		"DETAIL_URL" => "",
		"DISPLAY_ELEMENT_SELECT_BOX" => "Y",
		"ELEMENT_SORT_FIELD" => "sort",
		"ELEMENT_SORT_FIELD_BOX" => "name",
		"ELEMENT_SORT_FIELD_BOX2" => "id",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER_BOX" => "asc",
		"ELEMENT_SORT_ORDER_BOX2" => "desc",
		"FIELD_CODE" => array(
			0 => "NAME",
		),
		"HIDE_NOT_AVAILABLE" => "N",
		"IBLOCK_ID" => "13",
		"IBLOCK_TYPE" => "aspro_mshop_catalog",
		"NAME" => "CATALOG_COMPARE_LIST",
		"OFFERS_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"OFFERS_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"PRICE_CODE" => array(
			0 => "BASE",
		),
		"PRICE_VAT_INCLUDE" => "Y",
		"PRODUCT_ID_VARIABLE" => "id",
		"PROPERTY_CODE" => array(
			0 => "HIT",
			1 => "BRAND",
			2 => "VES_ATTR_S",
			3 => "VIDNOMENKLATURY_ATTR_S",
			4 => "KOD_ATTR_S",
			5 => "KOEFFITSIENT_EDINITSY_IZMERENIYA",
			6 => "SVYAZANNAYA_NOMENKLATURA_ATTR_S",
			7 => "SALE_TEXT",
			8 => "TIPNOMENKLATURY_ATTR_S",
			9 => "EXPANDABLES",
			10 => "CML2_ARTICLE",
			11 => "CML2_BASE_UNIT",
			12 => "IN_STOCK",
			13 => "VIDEO_YOUTUBE",
			14 => "FORUM_MESSAGE_CNT",
			15 => "vote_count",
			16 => "ASSOCIATED",
			17 => "CML2_MANUFACTURER",
			18 => "rating",
			19 => "CML2_TRAITS",
			20 => "CML2_TAXES",
			21 => "vote_sum",
			22 => "FORUM_TOPIC_ID",
			23 => "PROP_2033",
			24 => "SERVICES",
			25 => "CML2_ATTRIBUTES",
			26 => "COLOR_REF2",
			27 => "CML2_BAR_CODE",
			28 => "PROP_159",
			29 => "PROP_2052",
			30 => "PROP_2027",
			31 => "PROP_2053",
			32 => "PROP_2083",
			33 => "PROP_2049",
			34 => "PROP_2026",
			35 => "PROP_2044",
			36 => "PROP_162",
			37 => "PROP_2065",
			38 => "PROP_2054",
			39 => "PROP_2017",
			40 => "",
		),
		"SECTION_ID_VARIABLE" => "SECTION_ID",
		"SHOW_PRICE_COUNT" => "1",
		"TEMPLATE_THEME" => "blue",
		"USE_PRICE_COUNT" => "N",
		"COMPONENT_TEMPLATE" => ".default"
	),
	false
);?><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>